### ISSUE TITLE
Error cuando cargando el IGU/ Error when loading the IGU

### ISSUE THREAD

**Issue by SabineEgerer** [julienmalard/Tinamit#28]
**Describe el error**
Quiero usar el IGU como escribiendo aqui:
https://tinamit.readthedocs.io/es/latest/uso/IGU.html
con: 
from tinamit.Interfaz.IGU import correr

Pero parace como hay un error ortografico: Deberia ser 'cambiar_lengua' y no 'cambiar_leng', verdad?

I want to use IGU as described here:
https://tinamit.readthedocs.io/es/latest/uso/IGU.html
with:
from tinamit.Interfaz.IGU import correr

But it seems like there is a literal error: It should be 'cambiar_lengua' rather than 'cambiar_leng', right?

**Para reproducirlo**
Si lo encontraste con el IGU:
* La secuencia de botones que empujaste
from tinamit.Interfaz.IGU import correr

[autoreload of tinamit.Interfaz.Cajas failed: Traceback (most recent call last):
  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/home/egerer/Programme/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/egerer/Programme/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Interfaz/Cajas.py", line 9, in <module>
    from tinamit import cambiar_leng
ImportError: cannot import name 'cambiar_leng'
]

**Información adicional**
 - Versión de Python: 3.6
 - Versión de Tinamït 2.0
Uso Linux.

**Comment by julienmalard** [comment]
Sí, está ya arreglado en la nueva versión. Ver #29.
