### ISSUE TITLE
Problemas cargando el modelo SD (todavia)/ Problems when loading the SD model (still)

### ISSUE THREAD

**Issue by SabineEgerer** [julienmalard/Tinamit#29]
**Describe el error**
¿Qué pasó?
Todavia hay el problema que describe en #25 porque si uso pip install tinamit, el modelo SD con la terminacion .mdl no existe. Cuando copio el .mdl manual, hay otro error (vease abajo).

There is still the same problem as described in #25 because when I use pip install tinamit, the SD model with ending .mdl does not exist. When I copy the .mdl manually, there is another error (see below).

Si lo encontraste con el IPA:
* ```Una copia del código que llegó al error.```
https://github.com/julienmalard/Tinamit/blob/master/README.rst

Loading the .vpm SD model:
modelo.estab_mds('Prueba dll.vpm')
Traceback (most recent call last):

  File "<ipython-input-52-a16f051df391>", line 1, in <module>
    modelo.estab_mds('Prueba dll.vpm')

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 901, in estab_mds
    modelo_mds = generar_mds(archivo=archivo_mds)

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/EnvolturaMDS/__init__.py", line 50, in generar_mds
    '{}').format(''.join(['\n\t{}: {}'.format(env, e) for env, e in errores.items()])))

IndexError: tuple index out of range

Loading the .mdl SD model:

modelo.estab_mds('Prueba dll.mdl')
Traceback (most recent call last):

  File "<ipython-input-53-745f310ed4cf>", line 1, in <module>
    modelo.estab_mds('Prueba dll.mdl')

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 908, in estab_mds
    símismo.estab_modelo(modelo=modelo_mds)

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 90, in estab_modelo
    símismo.unidad_tiempo = símismo.obt_unidad_tiempo()

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 150, in obt_unidad_tiempo
    factor_conv = convertir(de=unid_mod_1, a=unid_mod_2)

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Unidades/Unidades.py", line 45, in convertir
    a = a.lower().replace(' ', '')

AttributeError: 'NoneType' object has no attribute 'lower'

**Información adicional**
 - Versión de Python 3.6
 - Versión de Tinamït 2.0
Uso Linux.

**Comment by julienmalard** [comment]
Hola,

Ah, es que hay que instalar la versión más recién de Tinamït, la cuál tiene el .mdl, y eso sin error.

Si quieres **usar** Tinamït:
```pip install git+https://github.com/julienmalard/tinamit.git@master```

Si quieres poder trabajar en y **modificar** Tinamït:
1. Crear una bifurcación de Tinamït ("Fork")
2. Clonar en tu compu con Pycharm VCS -> Checkout from version control
3. En la **terminal**, correr `python setup.py develop`

**Comment by julienmalard** [comment]
Cerrando por el momento...si queda problema siéntate libre de abrirlo de nuevo.

**Comment by SabineEgerer** [comment]
Vale, por el momento solamente quiero usar tinamit entonces use:
pip install git+https://github.com/julienmalard/tinamit.git@master

Pero, despues, cuando probe usar el IPA,habia otro error:

In [7]: from Conectado import Conectado
Traceback (most recent call last):

  File "<ipython-input-7-fdbc1be9e4cc>", line 1, in <module>
    from Conectado import Conectado

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Conectado.py", line 9, in <module>
    from tinamit.BF import EnvolturaBF, ModeloBF

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/__init__.py", line 3, in <module>
    from .Modelo import Modelo

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Modelo.py", line 17, in <module>
    import tinamit.Geog.Geog as Geog

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Geog/__init__.py", line 1, in <module>
    from .Geog import Geografía, Lugar

  File "/home/egerer/Programme/anaconda3/lib/python3.6/site-packages/tinamit/Geog/Geog.py", line 15, in <module>
    from تقدیر.ذرائع.مشاہدات import دن_مشا, مہنہ_مشا, سال_مشا

ModuleNotFoundError: No module named 'تقدیر'

Parace como la version mas recien no funcionar sin error :/
Puedes corregir otra vez?
Gracias!

**Comment by julienmalard** [comment]
Hola,

Parece que te falta la dependencia taqdir (es para cambios climáticos). Así que con:
```pip install git+https://github.com/julienmalard/taqdir.git@master```

...¡se debería arreglar!

Avísame por favor :)
-Julien

**Comment by SabineEgerer** [comment]
Muchas gracias por tu ayuda y respuestas rapidas! Todo se va bien ahora!
