### ISSUE TITLE
خطا در شبیه سازی مثال از تینامیت

### ISSUE THREAD

**Issue by includeamin** [julienmalard/Tinamit#30]
در شبیه سازی مثال زیر 
```
from tinamit.connected import Connected

model = Connected ()

model.estab_mds ('Test dll.vpm')
model.estab_bf ('Test bf.py')

model.connect (var_mds = 'Rain', var_bf = 'Rain', mds_source = False)
model.connect (var_mds = 'Forests', var_bf = 'Forests', mds_source = True)

res = model.simulate (step = 1, t_final = 100, name_curse = 'Corrida_Tinamit')
print (res)
```
خطا زیر رخ داد
```
AttributeError: 'NoneType' object has no attribute 'math'
```
که در نتیجه این خط بوده است
```
import pymc3 as pm
```

**Comment by julienmalard** [comment]
این دورست نیست
```python
from tinamit.connected import Connected
...
```
باید همه در زبان هسپانی باشه
```python
from tinamit.conectado import Conectado
...
```
(Tienes que escribir con las funciones de Tinamït, no con una versión aparamente traducida al inglés...no sé de dónde viene "Connected", "name_curse", "mds_source", etc. que no son variables o clases en Tinamït.)

Y, por favor:
* Copiar una copia **completa** del mensaje de error

**Comment by includeamin** [comment]
سلام  .بله من به زبان اسپانیایی نوشتم اما در اینجا توسط گوگل  ترجمه به انگلیسی شد
```
from tinamit.Conectado import Conectado

modelo = Conectado()

modelo.estab_mds('Prueba dll.vpm')
modelo.estab_bf('Prueba bf.py')

modelo.conectar(var_mds='Lluvia', var_bf='Lluvia', mds_fuente=False)
modelo.conectar(var_mds='Bosques', var_bf='Bosques', mds_fuente=True)

res = modelo.simular(paso=1, t_final=100, nombre_corrida='Corrida_Tinamit')
print(res)
```

**Comment by julienmalard** [comment]
Bueno entonces por favor escribir el código exacto y el **mensaje de error completo** que recibiste.

**Comment by includeamin** [comment]
```
/Users/mac/Desktop/FinalProject/venv/bin/python /Users/mac/Desktop/FinalProject/main.py
Traceback (most recent call last):
  File "/Users/mac/Desktop/FinalProject/main.py", line 1, in <module>
    from tinamit.Conectado import Conectado
  File "/Users/mac/Desktop/FinalProject/venv/lib/python3.6/site-packages/tinamit/Conectado.py", line 15, in <module>
    from tinamit.EnvolturaMDS import generar_mds
  File "/Users/mac/Desktop/FinalProject/venv/lib/python3.6/site-packages/tinamit/EnvolturaMDS/__init__.py", line 4, in <module>
    from tinamit.EnvolturaMDS.Vensim import ModeloVensim, ModeloVensimMdl
  File "/Users/mac/Desktop/FinalProject/venv/lib/python3.6/site-packages/tinamit/EnvolturaMDS/Vensim.py", line 11, in <module>
    from .sintaxis import sacar_arg, sacar_variables, juntar_líns, cortar_líns
  File "/Users/mac/Desktop/FinalProject/venv/lib/python3.6/site-packages/tinamit/EnvolturaMDS/sintaxis.py", line 478, in <module>
    'mín': {'vensim': 'MIN', 'pm': pm.math.minimum, 'python': min},
AttributeError: 'NoneType' object has no attribute 'math'

Process finished with exit code 1
```

**Comment by julienmalard** [comment]
Hola,
Para darle seguimiento (un poco tarde), la nueva versión de Tinamït debería arreglar los problemas descritos aquí. Voy a cerra este hilo, pero no dude en abrirlo de nuevo si queda duda.

Saludos
